// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function apply(f, x) {
  return Curry._1(f, x);
}

function add(x, y) {
  return x + y | 0;
}

function addFive(param) {
  return 5 + param | 0;
}

function applyTwice(f, x) {
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ch08_functionsContinued.res",
          26,
          27
        ],
        Error: new Error()
      };
}

function addOne(x) {
  return x + 1 | 0;
}

throw {
      RE_EXN_ID: "Assert_failure",
      _1: [
        "ch08_functionsContinued.res",
        33,
        13
      ],
      Error: new Error()
    };

exports.apply = apply;
exports.add = add;
exports.addFive = addFive;
exports.applyTwice = applyTwice;
exports.addOne = addOne;
exports.addTwo = addTwo;
exports.square = square;
exports.raiseToTheFourth = raiseToTheFourth;
exports.calc = calc;
exports.intId = intId;
exports.stringId = stringId;
exports.boolId = boolId;
exports.id = id;
exports.successor = successor;
/* addTwo Not a pure module */
