// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


if (4 !== Math.sqrt(16.0)) {
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ch16_ffi.res",
          16,
          0
        ],
        Error: new Error()
      };
}

console.log("heyo from js \\(^_^)/ ");

if (4 !== Math.sqrt(16.0)) {
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "ch16_ffi.res",
          40,
          0
        ],
        Error: new Error()
      };
}

console.log("heyo from js \\(^_^)/ with @bs.scope ");

/*  Not a pure module */
