// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function sayHi(param) {
  console.log("hi");
  
}

function isVowel(c) {
  switch (c) {
    case 98 :
    case 99 :
    case 100 :
    case 102 :
    case 103 :
    case 104 :
    case 106 :
    case 107 :
    case 108 :
    case 109 :
    case 110 :
    case 112 :
    case 113 :
    case 114 :
    case 115 :
    case 116 :
        return false;
    case 97 :
    case 101 :
    case 105 :
    case 111 :
    case 117 :
        return true;
    default:
      return false;
  }
}

exports.sayHi = sayHi;
exports.isVowel = isVowel;
/* No side effect */
